version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    env_file:
      - ./ui/.env
    depends_on:
      - api