version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    env_file:
      - ./ui/.env
    depends_on:
      - api

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: